flowchart TB

%% TOP ROW
subgraph TOP[Data Collection & Cleaning]
direction LR
    A[Define labels and keywords]
    B[Crawl images]
    C[Save raw images]
    D[Clean invalid images]
    E[Convert and rename]
    F[Detect duplicates]
    G{Duplicate?}

    A --> B --> C --> D --> E --> F --> G
end

%% BOTTOM ROW
subgraph BOTTOM[Preparation, Training & Evaluation]
direction LR
    I[Keep cleaned images]
    J[Manual review]
    K[Statistics]
    L[Upload to Kaggle]
    M[Train / Val / Test split]
    N[Preprocess and augment]
    O[Train MobileNet]
    P[Train ResNet50]
    Q[Evaluate]
    R[Compare results]
    S[Save best models]

    I --> J --> K --> L --> M --> N
    N --> O
    N --> P
    O --> Q
    P --> Q
    Q --> R --> S
end

H[Move to duplicates]

G -- Yes --> H
G -- No --> I
